# # Practice 3
import pandas as pd


# ## 1. Load the dataset & basic EDA
df = pd.read_csv("dataset/practice3.csv")

# From df.info() we can see no missing values in the dataset
df.info()

# Further explore on statistical value of age, price and quantity
df.describe()

# ## 2. Total revenue 
total_revenue = (df['price'] * df['quantity']).sum()
print('Total revenue:', total_revenue)

# ## 3. Average price and quantity of clothing each category
df.groupby('category').agg({'price': 'mean', 'quantity': 'mean'})

# ## 4. Group the dataset by the customer's age and gender and calculate the total revenue generated by each age/gender group.
df['revenue'] = df.price*df.quantity
df.groupby(['gender', 'age'])['revenue'].sum()

# ## 5. Top 3 cities of total revenue and insights on the factors that contributed to their success.
city_revenue_df = df.groupby('city').agg({'customer_id' : pd.Series.nunique,
                                       'age': 'mean',
                                       'category': list,
                                       'sub_category': list,
                                       'price': 'mean',
                                       'quantity': 'mean',
                                       'revenue': 'sum',
                                      })\
                .sort_values(by='revenue', ascending=False)

print("Top 3 cities of total revenue:")
city_revenue_df['revenue'].head(3)

"""
# From data explored on city_revenue_df, which each city has its mean age, mean price, mean quantity per customer, and their category purchased.
# We can conclude that highest revenue due to customers purchasing high-priced items like Suits, Dresses, Jeans. 
# Meanwhile, T-shirts is the lowest priced items and not contribute much to the revenue
# Some other factors such as age, gender is not likely affect the revenue
"""

# ## 6. Based on our analysis, we can provide the following recommendations to improve the online store's revenue and customer satisfaction:
"""
# Some of the ways the online store can improve its revenue and customer satisfaction based on the analysis are:
# 1. Promote high-priced items: As seen in the analysis, high-priced items like suits and party dresses contributed to the store's revenue. Promoting these items can attract customers who are willing to pay a premium for quality clothing.
# 2. Increase the quantity of items purchased: Customers purchasing multiple items in a single transaction can help increase the store's revenue. The online store can offer bundle deals or discounts for purchasing multiple items.
# 3. Improve the selection of items: Offering a wide range of clothing items in different categories can attract customers with different preferences. The online store can analyze the current trends and demand and offer items accordingly.
"""
